### ISSUE TITLE
cargo lambda watch infinite loop build

### ISSUE THREAD

**Issue by davehorner** [cargo-lambda/cargo-lambda#389]
I took the http-axum example from aws-lambda-rust-runtime and attempted to use it with cargo lambda.  The build works 
```
cargo lambda build
 INFO run: Changing profile to release mode. Cargo-lambda doesn't support building on debug mode on Windows
   Compiling proc-macro2 v1.0.51
   Compiling unicode-ident v1.0.6
   Compiling quote v1.0.23
   Compiling syn v1.0.109
   Compiling autocfg v1.1.0
   Compiling serde_derive v1.0.152
   Compiling serde v1.0.152
   Compiling pin-project-lite v0.2.9
   Compiling cfg-if v1.0.0
   Compiling futures-core v0.3.26
   Compiling memchr v2.5.0
   Compiling log v0.4.17
   Compiling libc v0.2.139
   Compiling slab v0.4.8
   Compiling futures-task v0.3.26
   Compiling futures-channel v0.3.26
   Compiling itoa v1.0.5
   Compiling futures-sink v0.3.26
   Compiling futures-util v0.3.26
   Compiling pin-utils v0.1.0
   Compiling fnv v1.0.7
   Compiling futures-io v0.3.26
   Compiling once_cell v1.17.1
   Compiling tokio v1.26.0
   Compiling tracing-core v0.1.30
   Compiling num_cpus v1.15.0
   Compiling socket2 v0.4.7
   Compiling mio v0.8.6
   Compiling tower-service v0.3.2
   Compiling rustversion v1.0.11
   Compiling percent-encoding v2.2.0
   Compiling httparse v1.8.0
   Compiling form_urlencoded v1.1.0
   Compiling num-traits v0.2.15
   Compiling ryu v1.0.12
   Compiling tower-layer v0.3.2
   Compiling try-lock v0.2.4
   Compiling serde_json v1.0.93
   Compiling want v0.3.0
   Compiling num-integer v0.1.45
   Compiling httpdate v1.0.2
   Compiling tinyvec_macros v0.1.1
   Compiling tinyvec v1.6.0
   Compiling futures-macro v0.3.26
   Compiling tokio-macros v1.8.2
   Compiling tracing-attributes v0.1.23
   Compiling pin-project-internal v1.0.12
   Compiling pin-project v1.0.12
   Compiling tracing v0.1.37
   Compiling async-trait v0.1.64
   Compiling unicode-normalization v0.1.22
   Compiling async-stream-impl v0.3.4
   Compiling futures-executor v0.3.26
   Compiling axum-core v0.3.2
   Compiling unicode-bidi v0.3.10
   Compiling mime v0.3.16
   Compiling idna v0.3.0
   Compiling async-stream v0.3.4
   Compiling futures v0.3.26
   Compiling axum v0.6.9
   Compiling overload v0.1.1
   Compiling lazy_static v1.4.0
   Compiling bitflags v1.3.2
   Compiling base64 v0.13.1
   Compiling http-range-header v0.3.0
   Compiling bytes v1.4.0
   Compiling serde_urlencoded v0.7.1
   Compiling query_map v0.6.0
   Compiling http v0.2.9
   Compiling chrono v0.4.23
   Compiling http-body v0.4.5
   Compiling http-serde v1.1.2
   Compiling aws_lambda_events v0.7.3
   Compiling serde_path_to_error v0.1.9
   Compiling tower v0.4.13
   Compiling hyper v0.14.24
   Compiling tokio-stream v0.1.12
   Compiling tower-http v0.4.0
   Compiling sharded-slab v0.1.4
   Compiling nu-ansi-term v0.46.0
   Compiling lambda_runtime_api_client v0.7.0
   Compiling lambda_runtime v0.7.3
   Compiling url v2.3.1
   Compiling thread_local v1.1.7
   Compiling encoding_rs v0.8.32
   Compiling sync_wrapper v0.1.2
   Compiling matchit v0.7.0
   Compiling lambda_http v0.7.3
   Compiling tracing-subscriber v0.3.16
   Compiling http-axum v0.1.0 (C:\working\website\http-axum)
    Finished release [optimized] target(s) in 1m 30s
```

However, if I cargo lambda watch it will compile for a while and then loop on forever.
```
c:\working\website\http-axum>cargo lambda watch
 INFO invoke server listening on 127.0.0.1:9000
 INFO starting lambda function function="http-axum" manifest="Cargo.toml"
   Compiling syn v1.0.109
   Compiling winapi v0.3.9
   Compiling windows-sys v0.45.0
   Compiling encoding_rs v0.8.32
   Compiling syn v1.0.109=====>         ] 94/139: windows-sys, winapi, encoding_rs, syn
   Compiling winapi v0.3.9
   Compiling windows-sys v0.45.0
   Compiling encoding_rs v0.8.32
   Compiling syn v1.0.109=====>         ] 94/139: winapi, encoding_rs, syn, windows-sys
   Compiling winapi v0.3.9
   Compiling windows-sys v0.45.0
   Compiling encoding_rs v0.8.32
   Compiling syn v1.0.109=====>         ] 94/139: windows-sys, syn, winapi, encoding_rs
   Compiling winapi v0.3.9
   Compiling windows-sys v0.45.0
   Compiling encoding_rs v0.8.32
   Compiling syn v1.0.109=====>         ] 94/139: encoding_rs, windows-sys, syn, winapi
   Compiling winapi v0.3.9
   Compiling windows-sys v0.45.0
   Compiling encoding_rs v0.8.32
   Compiling syn v1.0.109=====>         ] 94/139: syn, windows-sys, encoding_rs, winapi
   Compiling winapi v0.3.9
   Compiling windows-sys v0.45.0
   Compiling encoding_rs v0.8.32
   Compiling syn v1.0.109=====>         ] 94/139: encoding_rs, winapi, syn, windows-sys
   Compiling winapi v0.3.9
   Compiling windows-sys v0.45.0
   Compiling encoding_rs v0.8.32
   Compiling syn v1.0.109=====>         ] 94/139: encoding_rs, syn, winapi, windows-sys
   Compiling winapi v0.3.9
   Compiling windows-sys v0.45.0
   Compiling encoding_rs v0.8.32
```
The loop doesn't always happen on the 94th crate.  It varies. 
I've cargo clean and check'd with no success.  Not sure how to go about debugging this build concern.

**Comment by davehorner** [comment]
If you notice the cargo lambda build says:
`Cargo-lambda doesn't support building on debug mode on Windows`
it will force you to release.

If I run cargo run; it will build the debug build and produce the bootstrap.  Then a subsequent cargo lambda watch will run the pre-built debug build that was produced by cargo run.  If I edit files, subsequent monitor'd rebuilds will loop in a cargo build loop.

**Comment by greenwoodcm** [comment]
yeah i also think this is fixed by #378

**Comment by davehorner** [comment]
I did a cargo install cargo-lambda; I saw the 0.17.2 install.  I don't see a --version on these cargo commands so I didn't verify via invocation.  The new code does not fix the loop.  I still remain building the app with cargo run and doing cargo lambda watch to do local debugging.  I wouldn't close it if I'm voting.

**Comment by greenwoodcm** [comment]
i was able to do --version, can you try that to verify version?  also can you do your first cargo build before running watch, see if that changes the behavior?

**Comment by davehorner** [comment]
```
c:\working\website\http-axum>cargo lambda --version
cargo-lambda 0.17.2 (2023-03-04Z)
```

Sorry, I'm not sure why I didn't see that.  I think I did it on the watch subcommand.

I did a cargo clean and manually deleted target.
I ran a cargo lambda build; built successfully in release.
then ran cargo lambda watch; it did not pickup the prebuilt release binary, it compiles a new build.

```
  Compiling cc v1.0.79
   Compiling syn v1.0.109>              ] 92/187: windows-sys, syn, cc, winapi
   Compiling winapi v0.3.9
   Compiling windows-sys v0.45.0
   Compiling cc v1.0.79
   Compiling syn v1.0.109>              ] 88/187: syn, cc, winapi, windows-sys
   Compiling winapi v0.3.9
   Compiling windows-sys v0.45.0
   Compiling cc v1.0.79
   Compiling syn v1.0.109>              ] 88/187: winapi, syn, cc, windows-sys
   Compiling winapi v0.3.9
   Compiling windows-sys v0.45.0
   Compiling cc v1.0.79
   Compiling syn v1.0.109>              ] 92/187: cc, syn, winapi, windows-sys
   Compiling winapi v0.3.9
   Compiling windows-sys v0.45.0
   Compiling cc v1.0.79
   Compiling syn v1.0.109>              ] 90/187: windows-sys, cc, syn, winapi
   Compiling winapi v0.3.9
   Compiling windows-sys v0.45.0
   Compiling cc v1.0.79
   Compiling syn v1.0.109>              ] 91/187: windows-sys, cc, winapi, syn
   Compiling windows-sys v0.45.0
   Compiling winapi v0.3.9
   Compiling cc v1.0.79
   Compiling syn v1.0.109>              ] 87/187: windows-sys, winapi, syn, cc
   Compiling winapi v0.3.9
   Compiling windows-sys v0.45.0
   Compiling cc v1.0.79
    Building [===========>              ] 91/187: cc, windows-sys, winapi, syn
```
Stuck in a loop.

**Comment by greenwoodcm** [comment]
ooh, looking at your terminal path - did you do a straight clone of the project or did you just clone in the http-axum sun-directory?  avoiding this loop requires that the project .gitignore file or a parent directory's .gitignore file ignores the target directory.  in this repo, we rely on the repo root's .gitignore to do that for all target directories, including those in the example crates.  so if you cloned the subdirectory directly you're missing the .gitignore file that tells cargo watch to ignore the target.

**Comment by davehorner** [comment]
well, we found one thing.  I did not have the .gitignore file.  I copied the .gitignore from another.  It just has /target in it.
```
c:\working\website\http-axum>cargo lambda watch
 INFO invoke server listening on 127.0.0.1:9000
 INFO starting lambda function function="http-axum" manifest="Cargo.toml"
   Compiling http-axum v0.1.0 (C:\working\website\http-axum)
   Compiling http-axum v0.1.0 (C:\working\website\http-axum)bin)
   Compiling http-axum v0.1.0 (C:\working\website\http-axum)bin)
   Compiling http-axum v0.1.0 (C:\working\website\http-axum)bin)
   Compiling http-axum v0.1.0 (C:\working\website\http-axum)bin)
   Compiling http-axum v0.1.0 (C:\working\website\http-axum)bin)
   Compiling http-axum v0.1.0 (C:\working\website\http-axum)bin)
   Compiling http-axum v0.1.0 (C:\working\website\http-axum)bin)
   Compiling http-axum v0.1.0 (C:\working\website\http-axum)bin)
   Compiling http-axum v0.1.0 (C:\working\website\http-axum)bin)
   Compiling http-axum v0.1.0 (C:\working\website\http-axum)bin)
 INFO terminating lambda scheduler===> ] 186/187: http-axum(bin)
 INFO terminating lambda function function="http-axum"
```

That output looks funny.  The ) there.  hmm.

**Comment by greenwoodcm** [comment]
is cargo putting build artifacts in bin instead of in target?  that's sort of what is suggested by the odd-looking log line

**Comment by davehorner** [comment]
I'm not sure what bin you mean, but it isn't creating a bin folder in /target.

**Comment by davehorner** [comment]
```
warning: `http-axum` (lib) generated 1 warning (run `cargo fix --lib -p http-axum` to apply 1 suggestion)                                           Compiling http-axum v0.1.0 (C:\working\website\http-axum)                                                                                     
```
that gem shows up too.  am I building a lib, why is it telling me about http-axum the lib.

**Comment by greenwoodcm** [comment]
can you try the watch command with `RUST_LOG=trace`?  when i do so on linux i get tracelogs from watch that tell me the file system change that triggers it

**Comment by davehorner** [comment]
oh boy that's great.  thanks for the trace suggestion.

```
TRACE encode_headers: Server::encode status=204, body=None, req_method=Some(GET)
TRACE encode_headers: server body forced to 0; method=Some(GET), status=204
DEBUG flushed 349 bytes
TRACE flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
TRACE Conn::read_head
TRACE received 123 bytes
TRACE parse_headers: Request.parse bytes=123
TRACE parse_headers: Request.parse Complete(123)
DEBUG parsed 2 headers
DEBUG incoming body is empty
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: started processing request
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: finished processing request latency=0 ms status=204
TRACE encode_headers: Server::encode status=204, body=None, req_method=Some(GET)
TRACE encode_headers: server body forced to 0; method=Some(GET), status=204
DEBUG flushed 349 bytes
TRACE flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
TRACE Conn::read_head
TRACE received 123 bytes
TRACE parse_headers: Request.parse bytes=123
TRACE parse_headers: Request.parse Complete(123)
DEBUG parsed 2 headers
DEBUG incoming body is empty
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: started processing request
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: finished processing request latency=0 ms status=204
TRACE encode_headers: Server::encode status=204, body=None, req_method=Some(GET)
TRACE encode_headers: server body forced to 0; method=Some(GET), status=204
DEBUG flushed 349 bytes
TRACE flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
TRACE Conn::read_head
TRACE received 123 bytes
TRACE parse_headers: Request.parse bytes=123
TRACE parse_headers: Request.parse Complete(123)
DEBUG parsed 2 headers
DEBUG incoming body is empty
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: started processing request
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: finished processing request latency=0 ms status=204
TRACE encode_headers: Server::encode status=204, body=None, req_method=Some(GET)
TRACE encode_headers: server body forced to 0; method=Some(GET), status=204
DEBUG flushed 349 bytes
TRACE flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
TRACE Conn::read_head
TRACE received 123 bytes
TRACE parse_headers: Request.parse bytes=123
TRACE parse_headers: Request.parse Complete(123)
DEBUG parsed 2 headers
DEBUG incoming body is empty
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: started processing request
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: finished processing request latency=0 ms status=204
TRACE encode_headers: Server::encode status=204, body=None, req_method=Some(GET)
TRACE encode_headers: server body forced to 0; method=Some(GET), status=204
DEBUG flushed 349 bytes
TRACE flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
TRACE Conn::read_head
TRACE received 123 bytes
TRACE parse_headers: Request.parse bytes=123
TRACE parse_headers: Request.parse Complete(123)
DEBUG parsed 2 headers
DEBUG incoming body is empty
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: started processing request
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: finished processing request latency=0 ms status=204
TRACE encode_headers: Server::encode status=204, body=None, req_method=Some(GET)
TRACE encode_headers: server body forced to 0; method=Some(GET), status=204
DEBUG flushed 349 bytes
TRACE flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
TRACE Conn::read_head
TRACE received 123 bytes
TRACE parse_headers: Request.parse bytes=123
TRACE parse_headers: Request.parse Complete(123)
DEBUG parsed 2 headers
DEBUG incoming body is empty
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: started processing request
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: finished processing request latency=0 ms status=204
TRACE encode_headers: Server::encode status=204, body=None, req_method=Some(GET)
TRACE encode_headers: server body forced to 0; method=Some(GET), status=204
DEBUG flushed 349 bytes
TRACE flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
TRACE Conn::read_head
TRACE received 123 bytes
TRACE parse_headers: Request.parse bytes=123
TRACE parse_headers: Request.parse Complete(123)
DEBUG parsed 2 headers
DEBUG incoming body is empty
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: started processing request
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: finished processing request latency=0 ms status=204
TRACE encode_headers: Server::encode status=204, body=None, req_method=Some(GET)
TRACE encode_headers: server body forced to 0; method=Some(GET), status=204
DEBUG flushed 349 bytes
TRACE flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
TRACE Conn::read_head
TRACE received 123 bytes
TRACE parse_headers: Request.parse bytes=123
TRACE parse_headers: Request.parse Complete(123)
DEBUG parsed 2 headers
DEBUG incoming body is empty
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: started processing request
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: finished processing request latency=0 ms status=204
TRACE encode_headers: Server::encode status=204, body=None, req_method=Some(GET)
TRACE encode_headers: server body forced to 0; method=Some(GET), status=204
DEBUG flushed 349 bytes
TRACE flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
TRACE Conn::read_head
TRACE received 123 bytes
TRACE parse_headers: Request.parse bytes=123
TRACE parse_headers: Request.parse Complete(123)
DEBUG parsed 2 headers
DEBUG incoming body is empty
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: started processing request
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: finished processing request latency=0 ms status=204
TRACE encode_headers: Server::encode status=204, body=None, req_method=Some(GET)
TRACE encode_headers: server body forced to 0; method=Some(GET), status=204
DEBUG flushed 349 bytes
TRACE flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
TRACE Conn::read_head
TRACE received 123 bytes
TRACE parse_headers: Request.parse bytes=123
TRACE parse_headers: Request.parse Complete(123)
DEBUG parsed 2 headers
DEBUG incoming body is empty
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: started processing request
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: finished processing request latency=0 ms status=204
TRACE encode_headers: Server::encode status=204, body=None, req_method=Some(GET)
TRACE encode_headers: server body forced to 0; method=Some(GET), status=204
DEBUG flushed 349 bytes
TRACE flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
TRACE Conn::read_head
TRACE received 123 bytes
TRACE parse_headers: Request.parse bytes=123
TRACE parse_headers: Request.parse Complete(123)
DEBUG parsed 2 headers
DEBUG incoming body is empty
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: started processing request
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: finished processing request latency=0 ms status=204
TRACE encode_headers: Server::encode status=204, body=None, req_method=Some(GET)
TRACE encode_headers: server body forced to 0; method=Some(GET), status=204
DEBUG flushed 349 bytes
TRACE flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
TRACE Conn::read_head
TRACE received 123 bytes
TRACE parse_headers: Request.parse bytes=123
TRACE parse_headers: Request.parse Complete(123)
DEBUG parsed 2 headers
DEBUG incoming body is empty
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: started processing request
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: finished processing request latency=0 ms status=204
TRACE encode_headers: Server::encode status=204, body=None, req_method=Some(GET)
TRACE encode_headers: server body forced to 0; method=Some(GET), status=204
DEBUG flushed 349 bytes
TRACE flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
TRACE Conn::read_head
TRACE received 123 bytes
TRACE parse_headers: Request.parse bytes=123
TRACE parse_headers: Request.parse Complete(123)
DEBUG parsed 2 headers
DEBUG incoming body is empty
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: started processing request
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: finished processing request latency=0 ms status=204
TRACE encode_headers: Server::encode status=204, body=None, req_method=Some(GET)
TRACE encode_headers: server body forced to 0; method=Some(GET), status=204
DEBUG flushed 349 bytes
TRACE flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
TRACE Conn::read_head
TRACE received 123 bytes
TRACE parse_headers: Request.parse bytes=123
TRACE parse_headers: Request.parse Complete(123)
DEBUG parsed 2 headers
DEBUG incoming body is empty
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: started processing request
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: finished processing request latency=0 ms status=204
TRACE encode_headers: Server::encode status=204, body=None, req_method=Some(GET)
TRACE encode_headers: server body forced to 0; method=Some(GET), status=204
DEBUG flushed 349 bytes
TRACE flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
TRACE Conn::read_head
TRACE received 123 bytes
TRACE parse_headers: Request.parse bytes=123
TRACE parse_headers: Request.parse Complete(123)
DEBUG parsed 2 headers
DEBUG incoming body is empty
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: started processing request
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: finished processing request latency=0 ms status=204
TRACE encode_headers: Server::encode status=204, body=None, req_method=Some(GET)
TRACE encode_headers: server body forced to 0; method=Some(GET), status=204
DEBUG flushed 349 bytes
TRACE flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
TRACE Conn::read_head
TRACE received 123 bytes
TRACE parse_headers: Request.parse bytes=123
TRACE parse_headers: Request.parse Complete(123)
DEBUG parsed 2 headers
DEBUG incoming body is empty
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: started processing request
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: finished processing request latency=0 ms status=204
TRACE encode_headers: Server::encode status=204, body=None, req_method=Some(GET)
TRACE encode_headers: server body forced to 0; method=Some(GET), status=204
DEBUG flushed 349 bytes
TRACE flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
TRACE Conn::read_head
TRACE received 123 bytes
TRACE parse_headers: Request.parse bytes=123
TRACE parse_headers: Request.parse Complete(123)
DEBUG parsed 2 headers
DEBUG incoming body is empty
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: started processing request
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: finished processing request latency=0 ms status=204
TRACE encode_headers: Server::encode status=204, body=None, req_method=Some(GET)
TRACE encode_headers: server body forced to 0; method=Some(GET), status=204
DEBUG flushed 349 bytes
TRACE flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
TRACE Conn::read_head
TRACE received 123 bytes
TRACE parse_headers: Request.parse bytes=123
TRACE parse_headers: Request.parse Complete(123)
DEBUG parsed 2 headers
DEBUG incoming body is empty
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: started processing request
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: finished processing request latency=0 ms status=204
TRACE encode_headers: Server::encode status=204, body=None, req_method=Some(GET)
TRACE encode_headers: server body forced to 0; method=Some(GET), status=204
DEBUG flushed 349 bytes
TRACE flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
TRACE Conn::read_head
TRACE received 123 bytes
TRACE parse_headers: Request.parse bytes=123
TRACE parse_headers: Request.parse Complete(123)
DEBUG parsed 2 headers
DEBUG incoming body is empty
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: started processing request
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: finished processing request latency=0 ms status=204
TRACE encode_headers: Server::encode status=204, body=None, req_method=Some(GET)
TRACE encode_headers: server body forced to 0; method=Some(GET), status=204
DEBUG flushed 349 bytes
TRACE flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
TRACE Conn::read_head
TRACE received 123 bytes
TRACE parse_headers: Request.parse bytes=123
TRACE parse_headers: Request.parse Complete(123)
DEBUG parsed 2 headers
DEBUG incoming body is empty
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: started processing request
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: finished processing request latency=0 ms status=204
TRACE encode_headers: Server::encode status=204, body=None, req_method=Some(GET)
TRACE encode_headers: server body forced to 0; method=Some(GET), status=204
DEBUG flushed 349 bytes
TRACE flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
TRACE Conn::read_head
TRACE received 123 bytes
TRACE parse_headers: Request.parse bytes=123
TRACE parse_headers: Request.parse Complete(123)
DEBUG parsed 2 headers
DEBUG incoming body is empty
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: started processing request
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: finished processing request latency=0 ms status=204
TRACE encode_headers: Server::encode status=204, body=None, req_method=Some(GET)
TRACE encode_headers: server body forced to 0; method=Some(GET), status=204
DEBUG flushed 349 bytes
TRACE flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
TRACE Conn::read_head
TRACE received 123 bytes
TRACE parse_headers: Request.parse bytes=123
TRACE parse_headers: Request.parse Complete(123)
DEBUG parsed 2 headers
DEBUG incoming body is empty
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: started processing request
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: finished processing request latency=0 ms status=204
TRACE encode_headers: Server::encode status=204, body=None, req_method=Some(GET)
TRACE encode_headers: server body forced to 0; method=Some(GET), status=204
DEBUG flushed 349 bytes
TRACE flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
TRACE Conn::read_head
TRACE received 123 bytes
TRACE parse_headers: Request.parse bytes=123
TRACE parse_headers: Request.parse Complete(123)
DEBUG parsed 2 headers
DEBUG incoming body is empty
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: started processing request
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: finished processing request latency=0 ms status=204
TRACE encode_headers: Server::encode status=204, body=None, req_method=Some(GET)
TRACE encode_headers: server body forced to 0; method=Some(GET), status=204
DEBUG flushed 349 bytes
TRACE flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
TRACE Conn::read_head
TRACE received 123 bytes
TRACE parse_headers: Request.parse bytes=123
TRACE parse_headers: Request.parse Complete(123)
DEBUG parsed 2 headers
DEBUG incoming body is empty
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: started processing request
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: finished processing request latency=0 ms status=204
TRACE encode_headers: Server::encode status=204, body=None, req_method=Some(GET)
TRACE encode_headers: server body forced to 0; method=Some(GET), status=204
DEBUG flushed 349 bytes
TRACE flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
TRACE Conn::read_head
TRACE received 123 bytes
TRACE parse_headers: Request.parse bytes=123
TRACE parse_headers: Request.parse Complete(123)
DEBUG parsed 2 headers
DEBUG incoming body is empty
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: started processing request
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: finished processing request latency=0 ms status=204
TRACE encode_headers: Server::encode status=204, body=None, req_method=Some(GET)
TRACE encode_headers: server body forced to 0; method=Some(GET), status=204
DEBUG flushed 349 bytes
TRACE flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
TRACE Conn::read_head
TRACE received 123 bytes
TRACE parse_headers: Request.parse bytes=123
TRACE parse_headers: Request.parse Complete(123)
DEBUG parsed 2 headers
DEBUG incoming body is empty
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: started processing request
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: finished processing request latency=0 ms status=204
TRACE encode_headers: Server::encode status=204, body=None, req_method=Some(GET)
TRACE encode_headers: server body forced to 0; method=Some(GET), status=204
DEBUG flushed 349 bytes
TRACE flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
TRACE Conn::read_head
TRACE received 123 bytes
TRACE parse_headers: Request.parse bytes=123
TRACE parse_headers: Request.parse Complete(123)
DEBUG parsed 2 headers
DEBUG incoming body is empty
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: started processing request
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: finished processing request latency=0 ms status=204
TRACE encode_headers: Server::encode status=204, body=None, req_method=Some(GET)
TRACE encode_headers: server body forced to 0; method=Some(GET), status=204
DEBUG flushed 349 bytes
TRACE flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
TRACE Conn::read_head
TRACE received 123 bytes
TRACE parse_headers: Request.parse bytes=123
TRACE parse_headers: Request.parse Complete(123)
DEBUG parsed 2 headers
DEBUG incoming body is empty
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: started processing request
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: finished processing request latency=0 ms status=204
TRACE encode_headers: Server::encode status=204, body=None, req_method=Some(GET)
TRACE encode_headers: server body forced to 0; method=Some(GET), status=204
DEBUG flushed 349 bytes
TRACE flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
TRACE Conn::read_head
TRACE received 123 bytes
TRACE parse_headers: Request.parse bytes=123
TRACE parse_headers: Request.parse Complete(123)
DEBUG parsed 2 headers
DEBUG incoming body is empty
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: started processing request
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: finished processing request latency=0 ms status=204
TRACE encode_headers: Server::encode status=204, body=None, req_method=Some(GET)
TRACE encode_headers: server body forced to 0; method=Some(GET), status=204
DEBUG flushed 349 bytes
TRACE flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
TRACE Conn::read_head
TRACE received 123 bytes
TRACE parse_headers: Request.parse bytes=123
TRACE parse_headers: Request.parse Complete(123)
DEBUG parsed 2 headers
DEBUG incoming body is empty
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: started processing request
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: finished processing request latency=0 ms status=204
TRACE encode_headers: Server::encode status=204, body=None, req_method=Some(GET)
TRACE encode_headers: server body forced to 0; method=Some(GET), status=204
DEBUG flushed 349 bytes
TRACE flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
TRACE Conn::read_head
TRACE received 123 bytes
TRACE parse_headers: Request.parse bytes=123
TRACE parse_headers: Request.parse Complete(123)
DEBUG parsed 2 headers
DEBUG incoming body is empty
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: started processing request
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: finished processing request latency=0 ms status=204
TRACE encode_headers: Server::encode status=204, body=None, req_method=Some(GET)
TRACE encode_headers: server body forced to 0; method=Some(GET), status=204
DEBUG flushed 349 bytes
TRACE flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
TRACE Conn::read_head
TRACE received 123 bytes
TRACE parse_headers: Request.parse bytes=123
TRACE parse_headers: Request.parse Complete(123)
DEBUG parsed 2 headers
DEBUG incoming body is empty
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: started processing request
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: finished processing request latency=0 ms status=204
TRACE encode_headers: Server::encode status=204, body=None, req_method=Some(GET)
TRACE encode_headers: server body forced to 0; method=Some(GET), status=204
DEBUG flushed 349 bytes
TRACE flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
TRACE Conn::read_head
TRACE received 123 bytes
TRACE parse_headers: Request.parse bytes=123
TRACE parse_headers: Request.parse Complete(123)
DEBUG parsed 2 headers
DEBUG incoming body is empty
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: started processing request
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: finished processing request latency=0 ms status=204
TRACE encode_headers: Server::encode status=204, body=None, req_method=Some(GET)
TRACE encode_headers: server body forced to 0; method=Some(GET), status=204
DEBUG flushed 349 bytes
TRACE flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
TRACE Conn::read_head
TRACE received 123 bytes
TRACE parse_headers: Request.parse bytes=123
TRACE parse_headers: Request.parse Complete(123)
DEBUG parsed 2 headers
DEBUG incoming body is empty
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: started processing request
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: finished processing request latency=0 ms status=204
TRACE encode_headers: Server::encode status=204, body=None, req_method=Some(GET)
TRACE encode_headers: server body forced to 0; method=Some(GET), status=204
DEBUG flushed 349 bytes
TRACE flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
TRACE Conn::read_head
TRACE received 123 bytes
TRACE parse_headers: Request.parse bytes=123
TRACE parse_headers: Request.parse Complete(123)
DEBUG parsed 2 headers
DEBUG incoming body is empty
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: started processing request
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: finished processing request latency=0 ms status=204
TRACE encode_headers: Server::encode status=204, body=None, req_method=Some(GET)
TRACE encode_headers: server body forced to 0; method=Some(GET), status=204
DEBUG flushed 349 bytes
TRACE flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
TRACE Conn::read_head
TRACE received 123 bytes
TRACE parse_headers: Request.parse bytes=123
TRACE parse_headers: Request.parse Complete(123)
DEBUG parsed 2 headers
DEBUG incoming body is empty
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: started processing request
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: finished processing request latency=0 ms status=204
TRACE encode_headers: Server::encode status=204, body=None, req_method=Some(GET)
TRACE encode_headers: server body forced to 0; method=Some(GET), status=204
DEBUG flushed 349 bytes
TRACE flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
TRACE Conn::read_head
TRACE received 123 bytes
TRACE parse_headers: Request.parse bytes=123
TRACE parse_headers: Request.parse Complete(123)
DEBUG parsed 2 headers
DEBUG incoming body is empty
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: started processing request
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: finished processing request latency=0 ms status=204
TRACE encode_headers: Server::encode status=204, body=None, req_method=Some(GET)
TRACE encode_headers: server body forced to 0; method=Some(GET), status=204
DEBUG flushed 349 bytes
TRACE flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
TRACE Conn::read_head
TRACE received 123 bytes
TRACE parse_headers: Request.parse bytes=123
TRACE parse_headers: Request.parse Complete(123)
DEBUG parsed 2 headers
DEBUG incoming body is empty
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: started processing request
DEBUG request{method=GET uri=/.rt/http-axum/2018-06-01/runtime/invocation/next version=HTTP/1.1}: finished processing request latency=0 ms status=204
TRACE encode_headers: Server::encode status=204, body=None, req_method=Some(GET)
TRACE encode_headers: server body forced to 0; method=Some(GET), status=204
DEBUG received windows process notification sig=Interrupt
DEBUG Received SIGINT.
DEBUG flushed 349 bytes
TRACE processed signal into event event=Event { tags: [Source(Keyboard), Signal(Interrupt)], metadata: {} }
 INFO Initiating shutdown ...
TRACE flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
TRACE got event event=Event { tags: [Source(Keyboard), Signal(Interrupt)], metadata: {} } priority=Urgent
 INFO terminating lambda scheduler
DEBUG signal received, starting graceful shutdown
 INFO terminating lambda function function="http-axum"
TRACE urgent event, by-passing filters
TRACE Conn::read_head
TRACE deregistering event source from poller
DEBUG ending file watcher
TRACE event is the first, resetting throttle window
TRACE State::close_read()
DEBUG finishing subtask subtask=fs
TRACE still within throttle window, cycling elapsed=200ns
DEBUG read eof
DEBUG aborting subtask subtask=fs
TRACE waiting for event maxtime=2.9997093s
TRACE State::close_write()
TRACE State::close_read()
TRACE State::close_write()
TRACE flushed({role=server}): State { reading: Closed, writing: Closed, keep_alive: Disabled }
TRACE shut down IO complete
TRACE deregistering event source from poller
error: process didn't exit successfully: `target\debug\http-axum.exe` (exit code: 0xc000013a, STATUS_CONTROL_C_EXIT)
TRACE converting to ::Done status=ExitStatus(ExitStatus(3221225786))
TRACE supervisor: got out of loop, waiting once more
DEBUG supervisor: creating synthetic process completion event event=Event { tags: [Source(Internal), ProcessCompletion(Some(Exception(-1073741510)))], metadata: {} }
DEBUG supervisor: no more commands to supervise
TRACE supervisor: marking process as done
TRACE supervisor: closing supervisor task
TRACE got event event=Event { tags: [Source(Internal), ProcessCompletion(Some(Exception(-1073741510)))], metadata: {} } priority=Low
TRACE filterer_check: verdict pass=true
TRACE filter passed event
TRACE still within throttle window, cycling elapsed=17.9811ms
TRACE waiting for event maxtime=2.9819021s
TRACE disable_keep_alive; closing idle connection
TRACE State::close()
TRACE State::close_read()
TRACE State::close_write()
TRACE flushed({role=server}): State { reading: Closed, writing: Closed, keep_alive: Disabled }
TRACE shut down IO complete
TRACE deregistering event source from poller
DEBUG run: Shutdown successful. Subsystem states:
DEBUG run:     Lambda server                                  => OK
DEBUG run:     Lambda server/lambda scheduler                 => OK
DEBUG run:     Lambda server/lambda scheduler/lambda runtime  => OK
DEBUG aborting subtask subtask=action
DEBUG aborting subtask subtask=error_hook
DEBUG aborting subtask subtask=signal
```

**Comment by davehorner** [comment]
Any other ideas?

I've modified the sample; i have a templates folder.  I added /templates to the .gitignore in addition to the /target we spoke about before.
```
[35mTRACE[0m [1mrun[0m[2m:[0m[1mloading ignore file[0m[1m{[0m[3mfile[0m[2m=[0mIgnoreFile { path: "C:\\working\\website\\http-axum\\.gitignore", applies_in: Some("C:\\working\\website\\http-axum"), applies_to: Some(Git) }[1m}[0m[2m:[0m adding ignore line [3mline[0m[2m=[0m"/target"
[35mTRACE[0m [1mrun[0m[2m:[0m[1mloading ignore file[0m[1m{[0m[3mfile[0m[2m=[0mIgnoreFile { path: "C:\\working\\website\\http-axum\\.gitignore", applies_in: Some("C:\\working\\website\\http-axum"), applies_to: Some(Git) }[1m}[0m[2m:[0m adding ignore line [3mline[0m[2m=[0m"/templates"
```
If I edit a template file; the build launches again.  I also am seeing remove events coming from the debug folders in target.

```
[35mTRACE[0m [1mrun[0m[2m:[0m[1mloading ignore file[0m[1m{[0m[3mfile[0m[2m=[0mIgnoreFile { path: "C:\\working\\website\\http-axum\\.gitignore", applies_in: Some("C:\\working\\website\\http-axum"), applies_to: Some(Git) }[1m}[0m[2m:[0m adding ignore line [3mline[0m[2m=[0m"/target"
[35mTRACE[0m [1mrun[0m[2m:[0m[1mloading ignore file[0m[1m{[0m[3mfile[0m[2m=[0mIgnoreFile { path: "C:\\working\\website\\http-axum\\.gitignore", applies_in: Some("C:\\working\\website\\http-axum"), applies_to: Some(Git) }[1m}[0m[2m:[0m adding ignore line [3mline[0m[2m=[0m"/templates"
```
I haven't figured out how to prune the terminal escape sequences in the trace output; I can provide a file if that helps.

**Comment by davehorner** [comment]
I have a folder static that contains a .gitignore which is just *.  maybe you can reproduce?
If I delete that ignore file; the watch and build work.

It does work and gives me this in the loop of the watch at the end of the build.
```
ERROR command exited code=1==========> ] 186/187: http-axum(bin)
warning: `http-axum` (bin "http-axum") generated 4 warnings (run `cargo fix --bin "http-axum"` to apply 3 suggestions)
```
It's working though so I'm happy.  Thanks for your help.

**Comment by greenwoodcm** [comment]
what's the content of your `.gitignore` that doesn't work?  unclear from your previous message.  is it this?
```
/templates
/target
```

if that's what it is, I wonder if `.gitignore` is treating those as absolute paths instead of relative paths?  can you try:
```
templates
target
```

**Comment by davehorner** [comment]
the static folder was a bunch of files with a * in the .gitignore.  I just added my static folder to the top level .gitignore.  this can be closed.
